"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
[ ](fg:color_bg1 bg:color_bg1)\
$username\
[ ](fg:color_orange bg:color_orange)\
$directory\
[ ](fg:color_yellow bg:color_yellow)\
$git_branch\
$git_status\
[ ](fg:color_aqua bg:color_aqua)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$java\
$kotlin\
$python\
[ ](fg:color_blue bg:color_blue)\
$docker_context\
[ ](fg:color_bg3 bg:color_bg3)\
$fill\
$status\
[ ](fg:color_bg3 bg:color_bg3)\
$cmd_duration\
[ ](fg:color_blue bg:color_blue)\
$terraform\
[ ](fg:color_aqua bg:color_aqua)\
$container\
[ ](fg:color_yellow bg:color_yellow)\
$time\
[ ](fg:color_orange bg:color_orange)\
$line_break$character"""

add_newline = false

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#000000'
color_bg1 = '#ebdbb2'
color_bg3 = '#665c54'
color_purple = '#b16286'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_yellow = '#d79921'
color_orange = '#d65d0e'
color_red = '#fb4934'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Fedora = " "
Ubuntu = " "
Arch = " "

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user]($style)'

[directory]
style = "bg:color_yellow fg:color_fg0"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"~" = " ~"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ on $symbol $branch](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind)](fg:color_fg0 bg:color_aqua)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[cpp]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context)](fg:#83a598 bg:color_bg3)]($style)'

[fill]
symbol = '─'
style = 'white'

[status]
disabled = false
style = "bg:color_bg3"
format = '[[ $symbol $status](bold fg:color_red bg:color_bg3)]($style)'

[cmd_duration]
style = "bg:color_blue"
format = '[[ took $duration ](fg:color_fg0 bg:color_blue)]($style)'

[terraform]
style = "bg:color_aqua"
format = '[[ via $symbol$workspace](fg:color_fg0 bg:color_aqua)]($style)'

[container]
style = "bg:color_yellow"
format = '[[ in $name $symbol](fg:color_fg0 bg:color_yellow)]($style)'

[time]
disabled = false
time_format = "%T"
style = "bg:color_orange"
format = '[[ at $time  ](fg:color_fg0 bg:color_orange)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
